audio-pitch-correction=no

ytdl-format="bestvideo[height<=1440]+bestaudio/best"

ytdl-raw-options-append=extractor-args=youtube:player_client=web_safari

demuxer-max-bytes=500MiB
demuxer-max-back-bytes=100MiB

hwdec=auto-safe
