#####COLORS THEME#####
source = ~/.config/hypr/hyprlandconfigs/themes/mocha.conf

source = ~/.config/hypr/hyprlandconfigs/autostart.conf
source = ~/.config/hypr/hyprlandconfigs/keybinds.conf
source = ~/.config/hypr/hyprlandconfigs/customization.conf
source = ~/.config/hypr/hyprlandconfigs/windowsrules.conf
source = ~/.config/hypr/hyprlandconfigs/input.conf
source = ~/.config/hypr/hyprlandconfigs/monitors.conf


