
#################
### AUTOSTART ###
#################
exec-once = systemctl --user start hyprpolkitagent

exec-once = waybar & hypridle & awww-daemon & systemctl --user start mpd
exec-once = sleep 2 && easyeffects --hide-window
exec-once = steam -silent
exec-once = AyuGram -startintray
