
#################
### AUTOSTART ###
#################
exec-once = systemctl --user start hyprpolkitagent

exec-once = waybar & hypridle & swww-daemon & systemctl --user start mpd
exec-once = steam -silent
exec-once = Telegram -startintray
