##############################
### WINDOWS AND WORKSPACES ###
##############################


# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

windowrulev2 = float, title:^(Waypaper)$

windowrulev2 = float, title:^(wiremix)$
windowrulev2 = size 670 250, title:^(wiremix)$
windowrulev2 = move 1884 50, title:^(wiremix)$ #1244

windowrulev2 = float, title:^(Helvum - Pipewire Patchbay)$
windowrulev2 = size 782 527, title:^(Helvum - Pipewire Patchbay)$
windowrulev2 = move 1772 50, title:^(Helvum - Pipewire Patchbay)$ #1132

windowrulev2 = float,title:^(bluetui)$
windowrulev2 = size 520 493, title:^(bluetui)$
windowrulev2 = move 2034 50, title:^(bluetui)$ #1394

windowrulev2 = float, title:^(btop)$
windowrulev2 = size 800 483, title:^(btop)$
windowrulev2 = move 6 50, title:^(btop)$

windowrulev2 = float, title:^(calcurse)$
windowrulev2 = size 550 541, title:^(calcurse)$
windowrulev2 = move 2004 50, title:^(calcurse)$ #1364

windowrulev2 = float, title:^(impala)$
windowrulev2 = size 643 635, title:^(impala)$
windowrulev2 = move 1911 50, title:^(impala)$ #1271

windowrulev2 = float,title:^(powermenu)$
windowrulev2 = size 160 192, title:^(powermenu)$
windowrulev2 = move 2394 50, title:^(powermenu)$ #1754

windowrulev2 = float,title:^(applauncher)$
windowrulev2 = size 436 208, title:^(applauncher)$
windowrulev2 = move 1062 50, title:^(applauncher)$ #742

windowrulev2 = opacity 1, workspace:-98
