##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#
windowrule = match:title ^(Waypaper)$, float on

# Правый верхний угол (вычитаем точную ширину окна вместо window_w)
windowrule = match:title ^(wiremix)$, float on, size 670 250, move (monitor_w-670-6) 50
windowrule = match:title ^(Helvum - Pipewire Patchbay)$, float on, size 782 527, move (monitor_w-782-6) 50
windowrule = match:title ^(bluetui)$, float on, size 520 493, move (monitor_w-520-6) 50
windowrule = match:title ^(calcurse)$, float on, size 550 541, move (monitor_w-550-6) 50
windowrule = match:title ^(impala)$, float on, size 643 635, move (monitor_w-643-6) 50
windowrule = match:title ^(powermenu)$, float on, size 160 122, move (monitor_w-160-6) 50

# Левый верхний угол (тут ничего вычислять не надо, оставляем как есть)
windowrule = match:title ^(btop)$, float on, size 800 483, move 6 50
windowrule = match:title ^(battop)$, float on, size 800 483, move 6 50
windowrule = match:title ^(powermode)$, float on, size 200 102, move 6 50

# Центр сверху (подставляем 436)
windowrule = match:title ^(applauncher)$, float on, size 436 208, move ((monitor_w-436)/2) 50
